//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
	using System;
	using System.IO;
	
	
	public partial class cat {
		
		private UInt16 age;
		
		public cat(UInt16 _age) {
			this.age = _age;
		}
		
		public static cat Read(System.IO.BinaryReader reader) {
			UInt16 _age = reader.ReadUInt16();
			return new cat(_age);
		}
		
		public virtual void Write(System.IO.BinaryWriter writer) {
			writer.Write(this.age);
		}
	}
}
