//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
	using System;
	using System.IO;
	
	
	public partial class foo {
		
		private Int32 bar;
		
		private Byte baz;
		
		private cat pet;
		
		public foo(Int32 _bar, Byte _baz, cat _pet) {
			this.bar = _bar;
			this.baz = _baz;
			this.pet = _pet;
		}
		
		public static foo Read(System.IO.BinaryReader reader) {
			Int32 _bar = reader.ReadInt32();
			Byte _baz = reader.ReadByte();
			cat _pet = cat.Read(reader);
			return new foo(_bar, _baz, _pet);
		}
		
		public virtual void Write(System.IO.BinaryWriter writer) {
			writer.Write(this.bar);
			writer.Write(this.baz);
			this.pet.Write(writer);
		}
	}
}
